
export const CITIES = [
  "New York, USA",
  "London, UK",
  "Paris, France",
  "Tokyo, Japan",
  "Sydney, Australia",
  "Rome, Italy",
  "Vienna, Austria",
  "Berlin, Germany",
  "Munich, Germany",
  "Los Angeles, USA",
  "Chicago, USA",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Amsterdam, Netherlands",
  "Singapore, Singapore",
  "Hong Kong, China",
  "Dubai, UAE",
  "Bangkok, Thailand",
  "Seoul, South Korea",
  "Istanbul, Turkey",
  "Dublin, Ireland",
  "Prague, Czech Republic",
  "Stockholm, Sweden",
  "Copenhagen, Denmark",
  "Helsinki, Finland",
  "Oslo, Norway",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Brussels, Belgium",
  "Moscow, Russia",
  "St. Petersburg, Russia",
  "Beijing, China",
  "Shanghai, China",
  "Mumbai, India",
  "Delhi, India",
  "Rio de Janeiro, Brazil",
  "São Paulo, Brazil",
  "Buenos Aires, Argentina",
  "Mexico City, Mexico",
  "Cairo, Egypt",
  "Johannesburg, South Africa",
  "Cape Town, South Africa",
  "Nairobi, Kenya",
  "Lagos, Nigeria",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
];
